//DICTIONNAIRE
var tDico = ['ADAM','ADELE','ADRIEN','AGATHE','ALAN','ALEX','ALEXANDRA','ALEXANDRE','ALEXIA','ALEXIS','ALICE','ALICIA','AMANDINE','AMBRE','AMELIE','AMINE','ANAELLE','ANAIS','ANDREA','ANNA','ANTHONY','ANTOINE','ANTONIN','ARNAUD','ARTHUR','AUDREY','AURELIE','AURELIEN','AXEL','AXELLE','BAPTISTE','BASTIEN','BENJAMIN','BRYAN','CAMILLE','CANDICE','CARLA','CASSANDRA','CELIA','CHARLES','CHARLOTTE','CHLOE','CLAIRE','CLARA','CLARISSE','CLEMENCE','CLEMENT','CLEMENTINE','CLOE','COLINE','CORALIE','CORENTIN','DAMIEN','DAVID','DORIAN','DYLAN','ELISA','ELISE','ELODIE','ELOISE','ELSA','EMELINE','EMILIE','EMMA','ENZO','ERWAN','ESTEBAN','ESTELLE','ETHAN','EVA','EVAN','FANNY','FLAVIE','FLORIAN','GABIN','GABRIEL','GAETAN','GUILLAUME','HELOISE','HUGO','ILONA','INES','JADE','JEAN','JEANNE','JEREMY','JONATHAN','JORDAN','JULES','JULIA','JULIE','JULIEN','JULIETTE','JUSTINE','KEVIN','KILLIAN','KYLIAN','LAURA','LAURINE','LEA','LEANE','LENA','LENNY','LEO','LEONIE','LILIAN','LILOU','LINA','LISA','LISE','LOANE','LOGAN','LOIC','LOLA','LORENZO','LOU','LOUIS','LOUISE','LOUNA','LUCAS','LUCIE','LUNA','MAEL','MAELLE','MAELYS','MAEVA','MANON','MARGAUX','MARGOT','MARIE','MARINA','MARINE','MARION','MARIUS','MARTIN','MATEO','MATHEO','MATHIAS','MATHIEU','MATHILDE','MATHIS','MATHYS','MATTEO','MATTHIEU','MAXENCE','MAXIME','MEHDI','MELANIE','MELINA','MELISSA','MOHAMED','MORGANE','MYRIAM','NATHAN','NICOLAS','NINA','NOA','NOAH','NOE','NOEMIE','NOLWENN','OCEANE','OLIVIA','OPHELIE','PAUL','PAULINE','PIERRE','QUENTIN','RAPHAEL','RAYAN','REMI','ROBIN','ROMAIN','ROMANE','RYAN','SACHA','SALOME','SAMUEL','SARAH','SIMON','SOFIANE','SOLENE','THEO','THIBAULT','THIBAUT','THOMAS','TITOUAN','TOM','TONY','TRISTAN','VALENTIN','VALENTINE','VICTOR','VICTORIA','VINCENT','WILLIAM','YANIS','YANN','YASMINE','ZOE'];
var tLettres = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];

/*tLettres = genLettres();
function genLettres(){
	var i;
	var tLettre = [];
	for(i = 65; i <= 90; i++){
		tLettres[i-65] = String.fromCharCode(i);
	}
	alert(tLettre);
	return tLettre;

}*/
